stages:
  - stage
  - prod

deploy-stage:
  stage: stage
  when: manual
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-stage server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh staging Core-nest-backend-staging $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d Core-nest-backend ]]; then
          cd /home/ubuntu/Core-nest-backend
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf Core-nest-backend
        fi "

    - sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP  "git clone -b https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/Core-nest-backend.git"
    - sshpass -p $XPLOR_STAGE_PASSWORD scp .env $Xplor_Username@$XPLOR_STAGE_IP:/home/ubuntu/Core-nest-backend
    - sshpass -p $XPLOR_STAGE_PASSWORD ssh -tt $Xplor_Username@$XPLOR_STAGE_IP  "
        cd /home/ubuntu/Core-nest-backend && docker-compose up -d --build "
    - echo "https://xplor-core-nest-stage.thewitslab.com"

.deploy-prod:
  stage: prod
  when: manual
  tags:
    - gcp
  script:
    - echo "Deployment on xplor-prod Server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh prod Core-nest-backend-prod $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d Core-nest-backend ]]; then
          cd /home/ubuntu/Core-nest-backend
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf Core-nest-backend
        fi "

    - sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP  "git clone -b https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/Core-nest-backend.git"
    - sshpass -p $XPLOR_STAGE_PASSWORD scp .env $Xplor_Username@$XPLOR_STAGE_IP:/home/ubuntu/Core-nest-backend
    - sshpass -p $XPLOR_STAGE_PASSWORD ssh -tt $Xplor_Username@$XPLOR_STAGE_IP  "
        cd /home/ubuntu/Core-nest-backend && docker-compose up -d --build "
    - echo "https://xplor-core-nest-prod.thewitslab.com"