version: '3'
services:
  core_backend:
    container_name: Xplor-core-backend
    build: .
    restart: always
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - E_AUTH_URI=${E_AUTH_URI}
      - VC_URL=${VC_URL}
    ports:
      - 1067:${PORT}
    networks:
      - xplor-network

  core_mongodb:
    image: mongo:latest
    container_name: Xplor-mongo-service
    restart: always
    volumes:
      - mongo-data:/data/db
    # ports:
    #   - 27017:27017
    networks:
      - xplor-network

networks:
  xplor-network:
    external: true

volumes:
  mongo-data:
